- name: Install Gradle 8.4
      run: |
        wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip -O /tmp/gradle.zip
        unzip -q /tmp/gradle.zip -d /opt
        echo "/opt/gradle-8.4/bin" >> $GITHUB_PATH

    - name: Build APK
      # Burada ./gradlew yerine sadece gradle kullanıyoruz
      run: gradle assembleDebug --no-daemon
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"
